### ISSUE TITLE
tests fail for: UnicodeEncodeError: 'ascii' codec can't encode character u'\u0100' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by yurivict** [mcmtroffaes/pathlib2#30] opened 2017-06-15 16:48 UTC
Tests are:
```
python2 test_pathlib2.py
python2 test_pathlib2_with_py2_unicode_literals.py
```
They fail for 2.2.1 and 2.3.0.

**Comment by mcmtroffaes** [comment] 2017-06-16 07:29
You mean Python 2.2.1 and 2.3.0? The library is only tested against Python 2.6, 2.7, 3.2 and above. There's no intention to support Python 3.0 and 3.1 as these aren't widespread. There's also no intention to still support 2.5 or lower (2.5 received its last security update more than 6 years ago). That said, I'm happy to try to carry a patch if it's trivial.

**Comment by yurivict** [comment] 2017-06-16 14:01
2.2.1 and 2.3.0 are versions of pathlib2.
Python-2.7 is used.

**Comment by mcmtroffaes** [comment] 2017-06-16 14:21
Thanks for clarifying. However, I can't reproduce this problem. Both travis and appveyor pass the tests for Python 2.7, see for instance:

https://travis-ci.org/mcmtroffaes/pathlib2/jobs/242044376
https://ci.appveyor.com/project/mcmtroffaes/pathlib2/build/job/3c9l8j1nj429rc65

**Comment by yurivict** [comment] 2017-06-16 16:01
Something isn't platform-neutral.

**Comment by mcmtroffaes** [comment] 2017-06-22 07:49
Due to the "u'\u0100' in position 0" part, I suspect it results from test_unicode, which would point to a bug in either six or in Python itself for your platform. Can you provide a full backtrace?

**Comment by yurivict** [comment] 2017-06-22 14:58
Stacks are
```
ERROR: test_unicode (__main__.PosixPathAsPureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pathlib2.py", line 735, in test_unicode
    self.cls(six.unichr(0x0100))
  File "/usr/ports/devel/py-pathlib2/work/pathlib2-2.3.0/pathlib2.py", line 1191, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/ports/devel/py-pathlib2/work/pathlib2-2.3.0/pathlib2.py", line 847, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/ports/devel/py-pathlib2/work/pathlib2-2.3.0/pathlib2.py", line 834, in _parse_args
    parts.append(a.encode(sys.getfilesystemencoding()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0100' in position 0: ordinal not in range(128)
```
and
```
ERROR: test_unicode (__main__.PurePathTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pathlib2.py", line 735, in test_unicode
    self.cls(six.unichr(0x0100))
  File "/usr/ports/devel/py-pathlib2/work/pathlib2-2.3.0/pathlib2.py", line 806, in __new__
    return cls._from_parts(args)
  File "/usr/ports/devel/py-pathlib2/work/pathlib2-2.3.0/pathlib2.py", line 847, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/ports/devel/py-pathlib2/work/pathlib2-2.3.0/pathlib2.py", line 834, in _parse_args
    parts.append(a.encode(sys.getfilesystemencoding()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0100' in position 0: ordinal not in range(128)
```

**Comment by mcmtroffaes** [comment] 2017-06-23 12:05
Thanks for the detailed trace. The file system encoding of your platform is ascii which is rather unusual. Obviously the test should be skipped on such platform. I can add an extra check for that.

**Comment by yurivict** [comment] 2017-06-23 14:05
I think it is supposed to be utf8.
Do you have a simple test that shows that it is ascii?

**Comment by mcmtroffaes** [comment] 2017-06-23 14:15
```
import sys
print(sys.getfilesystemencoding())
```

**Comment by yurivict** [comment] 2017-06-23 15:37
It prints UTF-8.

**Comment by mcmtroffaes** [comment] 2017-06-26 10:49
Very weird... What if you insert ``print(sys.getfilesystemencoding())`` just before ``parts.append(a.encode(sys.getfilesystemencoding()))`` and rerun the test?

The only thing I can think of is that your test environment somehow sets the file system encoding to ascii, but I don't know how that could happen.

**Comment by yurivict** [comment] 2017-06-26 16:25
It fails:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    parts.append(a.encode(sys.getfilesystemencoding()))
NameError: name 'parts' is not defined
```

**Comment by honnibal** [comment] 2017-07-22 14:04
You might consider extending your travis.yml config to test different system locales. You can add a block like this:

```
env:
  - LC_ALL="en_US.ascii" 
  - LC_ALL="en_US.utf-8"
  -LC_ALL=""
```

This will extend your build matrix, so that your tests are run with those environment variables preset.

**Comment by mcmtroffaes** [comment] 2017-07-24 13:51
Thanks for the suggestion @honnibal 

@yurivict - If that part of the code worked before, then it shouldn't fail now with a NameError on parts - not sure what's going on. :-(

**Comment by mcmtroffaes** [comment] 2017-07-25 10:12
Should be fixed now. Thanks again @yurivict and @honnibal !

**Closed by mcmtroffaes** 2017-07-25 10:12 UTC
